### ISSUE TITLE
Ubuntu Mate - Mutiny Dock/Panel: Dock too easy to remove.

### ISSUE THREAD

**Issue by siabost9deas** [robint99/mate-dock-applet#103]
It took me a while to work out why my side panel launchers in Mutiny weren't showing all the features I expected and others were getting - minimise/un-minimise etc.
I had inadvertently removed the dock from the panel instead of unpinning the specific launcher as I had intended. Because I was then dragging app launchers on to the naked panel they worked in terms of launching apps but without the dock features.
It also took me a while to figure out how to get the dock back.

This is going to be very confusing to a newish user and it may be an idea to prevent the dock being so easily removed or offer an oops 'undo' feature as in Plasma 5.

And/or, as @elcste suggested in https://ubuntu-mate.community/t/mutiny-dock-panel-too-easy-to-remove-dock/14628
"One solution would be a MacOS-like "options" submenu (or call it something else) that could hold the options not related to the app, like Dock Prefs, About, Move, and Remove [Dock Apple] From Panel."
![mutiny_dock-panel](https://user-images.githubusercontent.com/21143312/29465077-dc22a2a8-842f-11e7-8440-275bef8fe461.png)

**Comment by CreamyCookie** [comment]
@siabost9deas I think this isn't something the developer(s) of mate-dock-applet can change. If you have a good idea for improving, this would be the right place to report this would be https://github.com/mate-desktop/mate-panel/issues

However, you can make it much harder to remove by clicking on "Lock To Panel", because then "Remove" is grayed out. 

![screenshot](https://user-images.githubusercontent.com/3063858/42836568-b2bb4514-89fb-11e8-8165-400b04b26f9e.png)

**Comment by CreamyCookie** [comment]
@robint99 Maybe I'm missing something, but I think this issue could be closed. (Besides not applying to the applet, the user also hasn't been active on GitHub for a while.)

**Comment by robint99** [comment]
Closing because the 'Remove from Panel' menu item is something the MATE panel adds, not the applet. Therefore this is not an applet problem.
