### ISSUE TITLE
Ubuntu Mate Mutiny: launcher continuously flashes/pulses in dock

### ISSUE THREAD

**Issue by siabost9deas** [robint99/mate-dock-applet#104]
I have had this issue with the Telegram launcher icon and, in the past, the Caja file manager icon. Currently it's only affecting the Telegram launcher.
Once launched, the icon continues to flash even after the program is completely shut down.
[Flashing Icon.mp4.zip](https://github.com/robint99/mate-dock-applet/files/1234921/Flashing.Icon.mp4.zip)

**Comment by aptanet** [comment]
I get this too on the current beta with all the available updates. The other thing I've noticed is that, with Telegram, it takes a reboot to get the icon there instead of the default cogs; that could be because mine is coming from the flexiondotorg ppa though.

I've seen the flashing with Telegram, Caja and Firefox so far and assume that somehow the notification that the application has stared is not getting picked up, which is then locking any change to 'not running' on close. That's just speculation though as I've not looked into how the flashing is managed, just assumed that it isn't simply flashing for a fixed period and does have some form of notification.

**Comment by oscardssmith** [comment]
I'm running into this as well. It's kind of annoying.

**Comment by uvwild** [comment]
ditto with dock applet 0.77 on a  mate 1.16 desktop on ubuntu 16.04 system

**Comment by jwhitbeck** [comment]
I had a similar problem. In my case it turned out that the bamfdaemon wasn't starting. I was able to work around that by adding the following systemd unit file.

`/etc/systemd/user/bamfdaemon.service.d/burst.conf`

```
[Unit]

StartLimitBurst=100
```

Then reload the user systemd units: `systemctl --user daemon-reload` and log-in/log-out.

**Comment by robint99** [comment]
Closing this I cannot duplicated. Also, I think its probably related to #139 which was fixed in V0.87.
