### ISSUE TITLE
Bad algorythm of *.desktop file search

### ISSUE THREAD

**Issue by alex4321** [robint99/mate-dock-applet#105]
Seems like there problem with algoryhm of searching desktop file

E.g. assume that I have netbeans that runned by command

    /bin/sh "/home/user/bin/netbeans-8.2/bin/netbeans"

in netbeans.desktop.

And I have vivaldi browser that runs by command like:

    ${EXC}vivaldi-snapshot${ETC}

In docked_app.py of installed applet I see next code:

    if "/" in de_exec:
        if de_exec.split("/")[-1] in self.cmd_line:
            exec_found = True

So - when it runned for vivaldi app and netbeans desktop pair:

    de_exec = "/bin/sh"
    self.cmd_line = ".../vivaldi-snapshot"
    de_exec.split("/")[-1] = "sh"
    de_exec.split("/")[-1] in self.cmd_line = True

So it map netbeans icon to vivaldi.

Seems like it'll be better to use code like next (it'll send pull request later):

    if "/" in de_exec:
        if ("/" + de_exec.split("/")[-1]) in self.cmd_line:
            exec_found = True

**Comment by robint99** [comment]
Sorry for not replying earlier to this, I'm a bad, bad person :disappointed: 

In V0.81 I completely changed the way in which apps are matched to their .desktop files, so I think your pull request is no longer necessary. Because of that, I'll close this issue, but if you still have problems, open another issue and I promise to be quicker in responding...
