### ISSUE TITLE
Palemoon Icon not showing

### ISSUE THREAD

**Issue by fugo** [robint99/mate-dock-applet#112]
I use dock 0.79 with Mint Mate 18.2 and my icon set is  [papirus-icon-theme :octocat:](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme) 

The Icon of one of my browsers [palemoon](http://www.palemoon.org/)  is not showing in the dock.
It lives @ /user/share/icons/Papirus/48x48/palemoon.svg
![palemoon](https://user-images.githubusercontent.com/469222/31236011-2b402106-a9f3-11e7-89e0-c0e414e3ee60.png)
What could I do? The actual icon is anoying because of not only one showing up
![icon](https://user-images.githubusercontent.com/469222/31236411-50f9fbe6-a9f4-11e7-902a-e2a004528a29.png)

**Comment by gsantner** [comment]
Post your palemoon.desktop file

**Comment by fugo** [comment]
sorry for the delay - here the desptop file

```
[Desktop Entry]
Version=1.0
Name=Pale Moon Web Browser
Comment=Browse the World Wide Web
Keywords=Internet;WWW;Browser;Web;Explorer
Exec=palemoon %u
Terminal=false
X-MultipleArgs=false
Type=Application
Icon=palemoon
Categories=Network;WebBrowser;Internet;
MimeType=text/html;text/xml;application/xhtml+xml;application/xml;application/rss+xml;application/rdf+xml;image/gif;image/jpeg;image/png;x-scheme-handler/http;x-scheme-handler/https;x-scheme-handler/ftp;x-scheme-handler/chrome;video/webm;application/x-xpinstall;
StartupNotify=true
Actions=NewWindow;NewPrivateWindow;

[Desktop Action NewWindow]
Name=Open a New Window
Exec=palemoon -new-window
OnlyShowIn=Unity;

[Desktop Action NewPrivateWindow]
Name=Open a New Private Window
Exec=palemoon -private-window
OnlyShowIn=Unity;
```

**Comment by robint99** [comment]
I've just made some major changes to the way the applet matches apps. Rather than trying to work it all out for itself it now uses the Bamf library (https://launchpad.net/bamf). This is the same library that Unity and Plank use for app matching, so if they work with Palemoon the applet will do  now also.

I've got some more changes to make, so I'll combine all the new stuff into a new version of to be released in a few weeks time. In the meantime I'm going to close this issue because of the new code it is no longer relevant.

Cheers.
