### ISSUE TITLE
Incorrect Icons when on Ubuntu Mate 17.10 (Mutiny)

### ISSUE THREAD

**Issue by oscardssmith** [robint99/mate-dock-applet#117]
Hi, I've noticed that some icons are consistently wrong in the dock. Specifically for me, Libre Office detects as Netbeans. I have no idea why this is happening. Any ideas? I can provide more info about my system, but I have no idea what else would be helpful.
I am running version .79-1

**Comment by robint99** [comment]
I've just made some major changes to the way the applet matches apps. Rather than trying to work it all out for itself it now uses the Bamf library (https://launchpad.net/bamf). This is the same library that Unity and Plank use for app matching, so the dock applet should now be as good as they are in doing this.

The code is already committed here on github, so if you're feeling brave you can try it yourself. If you do this though you'll need to install the bamf library (there may also be a bamf daemon package which also  needs to be installed) from your distro's package manager. This is pre-installed on Ubuntu Mate, so no worries there...

I've got some more changes to make, so I'll combine all the new stuff into a new version of to be released in a few weeks time. In the meantime I'm going to close this issue because it is no longer relevant.

Cheers.

**Comment by oscardssmith** [comment]
Thank you so much.
