### ISSUE TITLE
Nothing shows up in Linux Mint 18.2

### ISSUE THREAD

**Issue by Rydkey** [robint99/mate-dock-applet#118]
Hi,
I've followed the README.md (even for line --with-gtk3)
but when I go to add to panel and add Dock to it, dock don't shows up.
thanks for reading

**Comment by jibraniqbal666** [comment]
the same issue in Linux Mint 18.3, Installed from sources with gtk3 flag, can't see the dock. why? why?

**Comment by alleyoopster** [comment]
Same problem with Manjaro using Arch community GTK3 package 0.81-1  and mate-desktop 1.20

**Comment by alleyoopster** [comment]
OK solved for Arch. There is no dependancy for bamf set, it is required. Install and it works.

**Comment by Rydkey** [comment]
Works like a charm, Thanks  a lot.

**Comment by Rydkey** [comment]
For those who still struggle to launch the applet with GTK+3, here is the solution : 
_get the latest version from webupd8team ppa (0.79-1~webupd8~xenial1):
  sudo add-apt-repository ppa:webupd8team/mate
  sudo apt update
  sudo apt install mate-dock-applet

and then modify build_gtk2:
  sudo sed -i.bak s/build_gtk2\ =\ True/build_gtk2\ =\ False/g /usr/lib/mate-applets/mate-dock-applet/*.py_
see : https://bugs.launchpad.net/linuxmint/+bug/1706994

**Comment by machineghost** [comment]
@Rydkey 

1.  Thanks a ton for posting this
2. There is an extra `_` at the end of your `sudo sed` command
3. Do you need to re-install or re-compile dock applet after doing this, or do you need to logout and back in?  After I ran the command and tried to re-add the applet it still doesn't appear.

**Comment by Rydkey** [comment]
I had re-installed or re-compiled if I remember well.

**Comment by Isakku** [comment]
Well well. I have tried compiling on Mint 18.3 and had the same results: NOTHING shows up.
I think it is related to this issue:
https://github.com/robint99/mate-dock-applet/issues/109
Dependencies. It's always the dependencies!
I have tried downloading older source code from here and the last version I can succesfully compile is 
0.80. New dependency bamf was added for 0.81 
https://github.com/robint99/mate-dock-applet/commit/d9f005e6b86cae4be57a051058c3b3260036f2b5
And even if I try adding those I still have the same problem everyone else has: Nothing shows up.
So far I remember that has always been the problem. Adding the Webupd8 repo used to help before because it would give the real list of dependencies with exact names for my distro. It  didn't help this time because Webupd8 is quite outdated now (version 0.79?) 
So, when using the synaptic package manager to search for those bamf dependencies all I could find was this:
Bamf (bamfdaemon, libbamf and gir1.2-bamf)
bamfdaemon is there so I could find it and istall it.
libbamf doesn't give an exact match. What I have available is libbamf3-2 so that's what I installed.
gir1.2-bamf again not an exact match What I have available is gir1.2-bamf-3 so that's what I installed.
Again if that were all then I should be able to compile and run v0.81 but it doesn't seem to be the case.
All I can get to work is compiling v0,80.

**Comment by robint99** [comment]
I'm a bit late to the party but have finally looked into this. There are a few things going on here:

- the version of the applet in the Mint repositories is compiled for Gtk2, but Mint is providing Gtk3 versions of MATE desktop and because of this the applet won't work.
- the latest versions of the applet (0.81 and above) rely on features provided by Gtk3.22 and above. Mint 18.3 is still on 3.18 or 3.20 and this causes the applet to fall over..
- the applet has some new dependencies.

So, I've submitted a bug report to Linux Mint (here](https://github.com/linuxmint/linuxmint/issues/13) asking them if they could provide a later version of the applet compiled against gtk3. Since I did this I found out that the next version of Mint is due to be released in a [month or so](https://linuxhint.com/linux-mint-19-release-date/) so I don't know if the Mint developers will think it's worth making a change to 18.3 so late in its life. 

I've also updated the main page with some info about using the applet with Mint 18.2 or 3 - the latest version of the applet supported (0.80) and a link to the source. The list of dependencies has been updated too. 

Aside from doing this, I'm afraid that all I can suggest is that for now you manually install V0.80 and then wait for Mint 19 to be released.

Cheers.

**Comment by robint99** [comment]
Quick addendum:

For Ubuntu and Linux Mint I've written a makeshift program to automate the downloading and compiling of the applet, and as part of this it installs any missing dependencies. I've tested it on Ubuntu 16.04 and 18.04 (17.10 will probably work too but I havent' tested it) and Mint 18.3. On Ubuntu you get the very latest applet code from git. On Mint you get V0.80... Hopefully this might be of some use to you.

If you want to give it a try you can get it from this link (right click and do 'save as'). To run it, open up a terminal, cd to the directory where you save the file and do python3 da_installer.py

**Comment by robint99** [comment]
Closed as Mint 18.2 is no longer curtent.
