### ISSUE TITLE
Feature request: launch program from right click

### ISSUE THREAD

**Issue by oscardssmith** [robint99/mate-dock-applet#120]
With the current status of this, it is a pain to launch an application that is already open if you don't have a middle mouse button (laptop, or bad mouse). It would be great if there was a launch option when you right click on a program. Thanks.

**Comment by robint99** [comment]
Unfortunately, the applet never gets any right clicks because the MATE panel uses them to display context menus and doesn't pass them on.

However, the applet already has the ability to start another instance of an app that's already open. All you have to do is hold down the <shift> key and click the app icon.

Hope this helps, and sorry for the long delay in replying...
