### ISSUE TITLE
dock_applet.py crashed with SIGSEGV (whilst attempting to drag icons - i386)

### ISSUE THREAD

**Issue by rbshep78** [robint99/mate-dock-applet#125]
I'm having a problem with mate-dock-applet crashing while attempting to drag dock items around on Linux i386

I've reported the issue on launchpad (using ubuntu's '_apport_' tool) but i'm not sure how to debug (whether i need the source package for debugging symbols, how to use _mate-panel-test-applets_ etc.)

[https://bugs.launchpad.net/ubuntu/+source/mate-dock-applet/+bug/1752668](https://bugs.launchpad.net/ubuntu/+source/mate-dock-applet/+bug/1752668)

[https://ubuntu-mate.community/t/mate-dock-applet-crashes-when-moving-dock-items-i386/16093](https://ubuntu-mate.community/t/mate-dock-applet-crashes-when-moving-dock-items-i386/16093)

**Comment by robint99** [comment]
I recently changed the way drag and dropping works. Since then I haven't seen this bug, despite many attempts at trying to recreate it. Therefore I believe its fixed. I'll be releasing a new version of the applet in the next few days and it should work its way into Ubuntu MATE shortly afterwards. If you want to give it a try before then you can install the latest version of applet from source by going [here](https://github.com/robint99/misc).

I'll leave this issue open for the time being in case I'm being overly optimistic about having fixed it....

Cheers.
