### ISSUE TITLE
0.83 on UM 18.04 beta 1 does not allow to pin new applications

### ISSUE THREAD

**Issue by arxo** [robint99/mate-dock-applet#127]
- install UM 18.04 beta 1 in a VM
- add Dock Applet to panel
- start any application
- right click on application icon to open context menu
=> there is no "Pin this to the dock" menu entry anymore

**Comment by robint99** [comment]
I've just installed 18.04 and this is working fine for me. In the panel options tab of the dock preferences have you selected the 'Disable popup action list' option ? This is required to make the pin/unpin options appear in the right click menu...

**Comment by arxo** [comment]
That option was not selected. Selecting it makes pin/unpin appear.
However, this was not the case in earlier versions, even in alphas of UM 18.04 the pin/unpin was always there.
Actualy, I am kindof confused by this change.
What was the reasoning behind this? It only creates more confusion and makes the dock less user-friendly.

**Comment by robint99** [comment]
There hasn't been a change - the default behavior has always been to show the option on the right click menu. However, there are a couple of ways this default behavior can be overridden. Firstly, when the dock's settings are changed, the new settings are written to a file in ~/.config/  This is so that if e.g. if the dock is removed from a panel and then added to another one, the settings files can be read and all pinned apps etc. from the previous dock retained. 

Secondly, if MATE Tweak is used to select a layout containing a dock, that dock's settings take precedence over the default settings. These then get written to the settings file in ~/.config and persist if the dock is added to a new panel later on.

So,  without any other information I can only presume that you may have accidentally changed the right click option at some point, and then later on added the dock to a new panel...

Regards

**Comment by arxo** [comment]
I just tried this again with a fresh profile, thus using the default layout.
I immediately added the dock to the top panel, right-clicked on a running app icon => no pin/unpin entry.

And there definitely was a change - at least v0.77 on UM 16.04 with the PPA for MATE 1.16.2 there is no need to check "Disable popup action list".
I really suggest making pin/unpin always available in both popup and the right-click menu.
