### ISSUE TITLE
Drag'n'drop icon arranging

### ISSUE THREAD

**Issue by marsjaninzmarsa** [robint99/mate-dock-applet#13]
Instead or beside current "Move `app` to the left/right".

**Comment by robint99** [comment]
This is something I'm definitely intending on doing soon. The current way of rearranging icons is just too awkward and clunky....

**Comment by robint99** [comment]
Over the past few days I've been looking into implementing drag and drop, but it may have to wait a while... The applet is written in Python and unfortunately drag and drop support for Gtk 2 in Python is either broken or missing completely. However, it seems to be fully supported for Gtk 3.

I'll keep an eye open for this being fixed in Gtk 2, but drag and drop might not be added to the applet until after I've ported it to Gtk 3...

**Comment by robint99** [comment]
Drag and dropping of icons has now been added but is available for GTK3 builds of the applet.
