### ISSUE TITLE
Window preview for unfocused windows appears on top of quick menu

### ISSUE THREAD

**Issue by stuartlangridge** [robint99/mate-dock-applet#134]
When mousing over a dock applet icon for an app which is not the foreground app, mate-dock-applet shows a preview of that app's window. However, it _also_ shows the quickmenu for an app. These two appear on top of one another, which is confusing and not very pretty. Attached is a very simple video demonstrating this.

![demonstration](https://user-images.githubusercontent.com/4356350/39396002-3dc5f76a-4ade-11e8-9fc6-48f54b995e7a.gif)

**Comment by robint99** [comment]
What's happening here is that you obviously are running Compiz as your window manager and the 'Thumbnail Window Previews' plugin is enabled. Unfortunately this plugin displays the preview in a really inconvenient place for the dock, and compiz provides no way of changing where they pop up. All I can suggest if that you install Compiz Settings Manager and disable the plugin.

Incidentally, the dock does provide some integration with Compiz. If you go into preferences there's an option on the Windows tab to provide it. If selected, then instead of the popup list of windows an Exposé    type of view is displayed instead.  That's the idea anyway. While I was investigating this issue I found out there was a bug with the dock that stopped it from working. I've committed a fix for this now and all is working again. It does require that the D-Bus and Scale plugins are enabled in the compiz setting manager, but beware that Compiz seems a bit buggy in 18.04. I've found that in a vm the Fading Windows plugin (enabled by default) will crash Compiz when used with D-Bus. On real hardware, having both D-Bus and the Crash Handler plugins enabled at the same time will cause crashes too. On an Arch system the same plugins work fine together.

Anyway, the dock related part of all this is now fixed and as the window thumbnail can be prevented by disabling the appropriate Compiz plugin, I'll close this issue now.
