### ISSUE TITLE
Pop-up menus display incomplete

### ISSUE THREAD

**Issue by yetist** [robint99/mate-dock-applet#148]
The menu item that contains the action of the application is not long, and the upper and lower arrow should not be displayed.
![default](https://user-images.githubusercontent.com/665058/40705751-53102fba-641e-11e8-96d8-cf3fddbf5501.png)

**Comment by robint99** [comment]
Unfortunately, the applet can only add items to this menu but it has no control over how it is displayed. This  done by the MATE panel. Because of this I will close this issue, but you can let the MATE developers know of the problem by raising an issue [here](https://github.com/mate-desktop/mate-panel/issues).

Thanks
