### ISSUE TITLE
Feature request: "bring all windows forward" option

### ISSUE THREAD

**Issue by elcste** [robint99/mate-dock-applet#154]
As a longtime Mac user before switching to Linux/Ubuntu/MATE, I still miss the Mac dock's behavior. When an app has more than one window open and you click the app's dock icon, instead of a menu, it brings all windows of the app to the front (keeping the same relative order of that app's windows).

I'm not sure if this is even easily possible with Linux/X, but if it is I'd use it :-P

**Comment by robint99** [comment]
I've just committed a fix for this. The 'Windows' tab in the preferences dialog has been renamed to Behaviour' and now lets you select what happens when a running app's dock icon is clicked.

![screenshot at 2018-07-28 07-49-55](https://user-images.githubusercontent.com/10033637/43354162-e299b752-923e-11e8-919d-62682c951abd.png)

As you can see there's now an option to minimize/restore all of the app's open windows, as you requested. When restoring, the applet doesn't remember the full stacking order of the windows, but it does remember which window was last active and this window is the last to be restored and is made active again.

The second option allows the applet to integrate with Compiz if required (and has actually been in the applet for a while now), and if this is selected left clicking a dock icon will show an expose type 
view of the app's open windows. This does require that the D-Bus and Scale plugins are enabled in the compiz setting manager, but beware that as  as @edwin-v noted, Compiz seems a bit buggy in 18.04. I've found that in a VM  the Fading Windows plugin (enabled by default) will crash Compiz when used with D-Bus. On real hardware, having both D-Bus and the Crash Handler plugins enabled at the same time will cause crashes too. On an Arch system the same plugins work fine together.

Hope this all helps...

**Comment by elcste** [comment]
I finally had a chance to try this, and it's great — just what I was hoping for!

**Comment by vkareh** [comment]
@edwin-v - I can reproduce this crash and I've submitted a fix for it: #160
