### ISSUE TITLE
Add list of all apps windows to panel right click menu

### ISSUE THREAD

**Issue by brokoli-mate** [robint99/mate-dock-applet#165]
Add list of all apps windows when right mouse button clicking on the app icon and/or to the popup menu

**Comment by robint99** [comment]
The applet can already display a list of all open windows. All you have to do is left click the app icon and a pop-up appears, e.g.

![165](https://user-images.githubusercontent.com/10033637/51520951-00558400-1e1d-11e9-888b-317fe64a4d4c.png)

Because of this I'll close this issue. Hope this helps, and sorry for the delay in looking into this :)
