### ISSUE TITLE
Adding window thumbnail previews to mate-dock-applet?

### ISSUE THREAD

**Issue by kq01526** [robint99/mate-dock-applet#49]
Hi @robint99 ,

is it possible to use window thumbnail previews with mate-dock-applet like in the Windows 7 / 8 / 10 taskbar as shown in the following screenshots for example:

**Windows 7:**
![Image](https://i-msdn.sec.s-msft.com/dynimg/IC420541.png)
[Source](https://msdn.microsoft.com/en-us/library/windows/desktop/dd378460%28v=vs.85%29.aspx#thumbnails)

**Windows 10:**
![Image](http://i.stack.imgur.com/Zg3EK.png)
[Source](http://superuser.com/questions/958690/how-to-make-windows-10-taskbar-thumbnail-previews-bigger)

?

If yes: How?

Regards

**Comment by robint99** [comment]
Its not possible with the applet at the moment, but I'll definitely look at adding it at some point in the future. I don't know when exactly that will be though - top of the list is adding Gtk3 support for Mate 1.14....

**Comment by Isakku** [comment]
Oh that would be awesome! +1 I support this idea!

**Comment by NoXPhasma** [comment]
That would be a nice feature for sure. But is that even possible with plain python3? I think this would probably need to be done by the composite manager and since we can use so many different once in Linux (and not all support such fancy stuff), this would be probably only work on specific ones (Compiz for example).

Correct me if I'm wrong.

**Comment by robint99** [comment]
At the moment I don't know if it is possible or not. As I said above, it's something I'm going to look at in the future, but I'd hope to be able to do it because it would be cool :). I'm not sure it would need a compositing window manager though, I seem to remember seeing thumbnail versions of window contents being displayed in the workspace swtichers of some old school window managers/DEs like Enlightenment 16 or FVWM. Suppose it just depends what Marco can do...

Cheers

**Comment by kq01526** [comment]
@robint99 :

DockBarX can do it when using KWin or Compiz with the KDE compatibility plugin, since KWin allows to access the window thumbnails through dbus, see following comment from @M7S :

https://bugs.launchpad.net/dockbar/+bug/1329241/comments/1

:wink:

**Comment by robint99** [comment]
Thanks for the info, I'll look into this

:)

**Comment by robint99** [comment]
I've just released a version of the applet which provides thumbnail previews, although not exactly in the way you wanted... 

The only way to do this is by using Compiz as the window manager - marco and compton just don't support it. If an app has more than one window open and you click it's dock icon, you can now get something like this:

![5f9caa2c-8493-11e6-82e3-46fa6b5b2365](https://cloud.githubusercontent.com/assets/10033637/18867781/7de61c70-849d-11e6-8195-a381e66a0b80.png)

Full details are in the release notes for V0.75 [here.](https://github.com/robint99/mate-dock-applet/releases)

If you activate the Windows Thumbnail Previews plugin in Compiz Config Settings Manager you'll also get a popup when the mouse hovers over the a dock icon, but as far as I can tell can only displays  thumbnail of the app's currently active window only, not all open windows...

I realise that this isn't exactly what was requested but it seems that its the best that can be done and on that basis I'll close this issue. Feel free to reopen or comment further if you have more info/suggestions.

**Comment by NoXPhasma** [comment]
You can display previews for all opened windows with the compiz thumbnail feature. [DockBarX](https://github.com/M7S/dockbarx) has done it for a long time, which is written in python too.

If I remember correctly you need to activate "Keep preview of minimized windows" from the "Workaround" Plugin.

**Comment by robint99** [comment]
Unfortunately I had all of the settings you mentioned already activated. However, as soon as I get the chance I'll have a look at the DockbarX code and see how it works....

Cheers...

**Comment by kq01526** [comment]
>  @robint99 wrote:
> Feel free to reopen or comment further if you have more info/suggestions.

Looks like I do not have the sufficient permissions in this repository to reopen this issue.

Could you please reopen it?

> @robint99 wrote:
> The only way to do this is by using Compiz as the window manager - marco and compton just don't support it.

Not true. I already told you that Kwin also supports it.

Also, I also already told you that you need to activate the ***KDE Compatibility Plugin*** and enable ***Support Plasma Thumbnails*** in Compiz Config Settings Manager, see:

![Image](http://ubuntuguide.net/wp-content/uploads/2010/12/KDEcompatibility.png)
[Source1](http://ubuntuguide.net/install-dockbarx-in-avant-window-navigator-in-ubuntu)
[Source2](https://bugs.launchpad.net/dockbar/+bug/1329241/comments/1)


> @robint99 wrote in https://github.com/robint99/mate-dock-applet/releases/tag/V0.75 :
> It seems that Compiz does not display or allowed selection of minimized windows

Not really true, since at least Kwin allows it, see:

![Image](https://cloud.githubusercontent.com/assets/16294493/19154322/5d51aa26-8bda-11e6-940b-3ce74df4c32f.png)

:slightly_smiling_face: 
> @robint99 wrote:
> I'll have a look at the DockbarX code and see how it works

Thank you.

**Comment by robint99** [comment]
> >@robint99 wrote:
> >The only way to do this is by using Compiz as the window manager - marco and compton just don't support it.

>Not true. I already told you that Kwin also supports it.

The vast majority of users are going to to stick with Marco, Compton or Compiz, since MATE Tweak makes it easy to switch between any of these. KWin is not something the average user is going to want to use as a window manager, or even be aware that they can use it.

I tried those KDE Compiz settings you mentioned, they had no effect at all with Compiz and CCSM 1.0.9.12.2 on Ubuntu MATE 16.04. I don't have a 16.10 machine or VM handy to try it on right now, but I'll give it a go when it's officially released next week...

>>@robint99 wrote in https://github.com/robint99/mate-dock-applet/releases/tag/V0.75 :
>>It seems that Compiz does not display or allowed selection of minimized windows

>Not really true, since at least Kwin allows it by setting Keep window thumbnails to Always

Yes, but I was talking about Compiz, not Kwin... 

If what you're really after is kwin support I think the best thing would be for you to open a new issue specifically for that. Bear in mind though that this would be a very low priority for me for because most users will not be using Kwin.

Having said that though, I do still have to look at the DockBarX code (my free time is limited at the moment, but I'm getting around to it) and it may be that once I do I'll find out how to produce thumbnails without resorting to kwin :grin: 

Cheers

**Comment by kq01526** [comment]
@robint99 :

There's now a Cinnamon panel item which also supports it, see: https://cinnamon-spices.linuxmint.com/applets/view/16 . So, apparently with Muffin (Cinnamon window manager and compositor, forked from Mutter) it can also be done. That being said:

> The vast majority of users are going to to stick with Marco

Let's see what the Marco devs have to say:

https://github.com/mate-desktop/marco/issues/307

;)
