### ISSUE TITLE
Strange problem in Linux Mint Mate 17.3

### ISSUE THREAD

**Issue by Isakku** [robint99/mate-dock-applet#51]
Since I'm using Linux Mint Mate 17.3 I followed the instructions stated here:
https://github.com/robint99/dock-applet/blob/master/README.md
in the "Other distributions" section
and then right clicked the panel and added the dock-applet.
It simply added application grouped buttons to the panel instead of replacing the current buttons with application grouped ones... now I have two buttons ... pff... 

screenshot:
![bug screenshot at 2016-05-25](https://cloud.githubusercontent.com/assets/16464336/15549443/884c9408-227a-11e6-8b68-04b754120e51.png)

**Comment by kq01526** [comment]
> @Isakku wrote:
> 
> pff...

You might want to ask yourself if that is the proper attitude when asking for support for the first time on this repository?

> @Isakku wrote:
> 
> It simply added application grouped buttons to the panel
> instead of replacing the current buttons with application grouped ones...
> now I have two buttons

As already mentioned in https://github.com/M7S/dockbarx/issues/24, you simply haven't set up your panels properly.

> @Isakku wrote:
> 
> and then right clicked the panel and added the dock-applet.

Yeah, and now you would simply need to remove the other buttons (the other panel applet, what's labels as "Linux Mint Mate buttons" in your screenshot) from the panel by right clicking on them and selecting "Remove From Panel".

However, I just had a look at it, and right clicking on the default buttons panel applet does not seem to allow selecting "Remove From Panel".

But there's a simple workaround:

Just remove the entire panel and create a new one and then add whatever applets you want to it (including mate-dock-applet).

:wink:

If you have only one panel at the moment, you first need to add a second panel and then remove the first panel, since you can not have zero panels.

Regards

**Comment by Isakku** [comment]
>@kq01526  wrote:
>You might want to ask yourself if that is the proper attitude when asking for support for the first >time on this repository?

Sorry. I just copied and pasted what I already said in the other thread. 
I'm just tired, this has been hard. I have had to fight my way to make things work the way I want but nothing seems to work well. 

>@kq01526  wrote:
>However, I just had a look at it, and right clicking on the default buttons panel applet does not >seem to allow selecting "Remove From Panel".

That's why I thought this was a bug, since it's not possible to remove them, I thought this software would do something about it but it doesn't.

>@kq01526  wrote:
>But there's a simple workaround:
>
>Just remove the entire panel and create a new (empty) one and then add whatever applets you >want to it (including mate-dock-applet).

Thanks a lot for your replies. I appreciate your effort.

The problem is that the workaround you suggest doesn't work.
I cannot add all the applets that are in the original panel! 
I can't even add add a simple volume control or network indicator! 
I could add the clock, the show desktop button, the mate-dock-applet and the mint menu, but they don't arrange correctly either. 

![screenshot at 2016-05-26rant](https://cloud.githubusercontent.com/assets/16464336/15580860/2d845f60-2338-11e6-8f6c-d34f9e79bdfc.png)

**Comment by kq01526** [comment]
> @Isakku wrote:
> 
> I cannot add all the applets that are in the original panel!

Yeah, I've also noticed that. Googled a bit on this issue but couldn't find a solution for it so far.

Anyway, I am not using MATE. I am using XFCE. I just had a look at MATE and the mate-dock-applet because [DockBarX](https://github.com/M7S/dockbarx) stopped working with newer versions of Ubuntu, so was looking for an alternative.

But since the new version of DockBarX is working on newer versions of Ubuntu now, I am continuing to use XFCE with the [xfce4-dockbarx-plugin](https://github.com/TiZ-EX1/xfce4-dockbarx-plugin).

Xubuntu 16.04 + DockBarX + [xfce4-dockbarx-plugin](https://github.com/TiZ-EX1/xfce4-dockbarx-plugin) is working just fine and does not have such issues like Linux Mint MATE 17.3 + mate-dock-applet.

For window thumbnail previews you unfortunately would need to replace the XFCE compositor with Compiz or KWin though, see: https://github.com/M7S/dockbarx/issues/3.

Regards

**Comment by robint99** [comment]
This issue seems to be more about problems setting up MATE panels than it is to do with the dock applet, but I can offer some assistance....

If you want the dock applet to open another instance of a program rather than activating a previously opened  window all you have to do is hold down the shift key when clicking the app's dock icon. No need for you to produce a new version at all ;)

As you seem to be having a lot of trouble setting up your panels you might want to take a look at Mate Tweak. I don't know if Mint is using the same version of Tweak as Ubuntu 16.04, but in Ubuntu it allows you to select several different panel layouts, one of which includes the dock applet. Once you've selected a layout you can configure the panels and applets as you like and when you're happy, save the layout to your own custom configuration. 

You may also find [this](http://www.youtube.com/watch?v=Qpy1s-JornY) video useful. It demonstrates how to setup a MATE panel with the dock applet, a workspace switcher and trash applet.

Regards

**Comment by Isakku** [comment]
>@robint99  wrote:
>
This issue seems to be more about problems setting up MATE panels than it is to do with the dock applet

Hmm... no. it became that way because unlike what I expected, the dock applet doesn't transform nor replace the buttons  with application grouped ones... thus now I have two buttons!
There's no way to remove those buttons! so the suggested workarounds imply messing with panels to see if setting them up somehow I will get anything to work.


... everything started with this:

It was supposed to be possible using dockbarx, but dockbarx no longer works.
now all I want is the grouped window functionality, but not the way it currentl works: alongside standard window functionality, I thought that since dockbarx no longer works, dock applet would do the same, and hoping to someday also get the thumbnail previews. ;)

>@robint99  wrote:
>
If you want the dock applet to open another instance of a program rather than activating a previously opened window all you have to do is hold down the shift key when clicking the app's dock icon. No need for you to produce a new version at all ;)


Thank you a lot for your help! 
hmm... no, I do not want to hold shift every time. I want that behavior to be turned on with an option and become permanent with that configuration. And I want that behavior to recognize if I am in the same workspace or not!
Anyways, Since I mostly program for windows, I don't have much experience with python. I have installed IDLE but there's still much I need to understand to get things done. Any advices? What tools do you use to work?

Regards

**Comment by NoXPhasma** [comment]
About your problems with adding some applets to the new panel, this is because some applets can only be placed once. That said, just delete your default panel and then add all the stuff you want to use to the new one.

If you think this should be handled different, you need to contact the developers of the [mate-desktop](https://github.com/mate-desktop/).

**Comment by robint99** [comment]
I'm relatively new to Python and applet development myself, so there isn't much advice I can give. Much of the info you'll find on Google is old and out of date, but two good places to go are [the Python Gtk API reference](https://lazka.github.io/pgi-docs/) (it's Gtk3 but much of it is still relevant to Gtk2, and in any case the applet will shortly be available for Gtk3 - I'm working on that now...), and [the MATE applet repository on github](https://github.com/mate-desktop/mate-applets). 

As for tools I use, I use vim for editing (might switch to Atom soon though because of how well it integrates with github) and [autotools] (https://www.gnu.org/software/automake/manual/html_node/Autotools-Introduction.html) for building and installing the applet.

Cheers

**Comment by Isakku** [comment]
Finally managed to solve this... it was unexpectedly easy, but had it's tidbits and pitfalls. I guess someone that doesn't know the smallest bit of everything would just give up in frustration. I mean I think it could even deserve a small tutorial.
So after installing mate dock applet I was unable to remove the normal buttons applet in the panel.  Right clicking the windows buttons only gave a common context menu. 

![screenshot at 2016-06-07 21 48 37](https://cloud.githubusercontent.com/assets/16464336/16384637/b6891c28-3c57-11e6-86e5-c7e5abb65303.png)

The applet options didn't seem to be anywhere. So, after feeling right clicking everywhere in despair, I found them.
For some reason, developers of the mate desktop decided to put the options for the window list applet within a tiny separator, that is so small that it's hardly noticeable (and even when I noticed it, I thought it was just a separator or that it belonged to the neighbor applet)  . Right clicking that thing gave the applet options context menu and the option to get rid of the applet.

![screenshot at 2016-06-07 21 47 32](https://cloud.githubusercontent.com/assets/16464336/16384665/d8ededfc-3c57-11e6-9acf-e8b0dcec771c.png)

With that done I was finally able to use mate-dock-applet. 
However I have noticed that when I use the show desktop button, it messes up the windows list, and I can only use alt tab to restore the windows (finally solved that too, I had key conflicts in the Compiz Config Settings Manager, I would report the bug but I don't know where, but I digress)
The point is that after pressing the show desktop button and then, click for example pluma, then firefox (both were open before) only pluma will show up, firefox icon will blink, but nothing else.
