### ISSUE TITLE
Launcher item click on foreground app minimises its windows

### ISSUE THREAD

**Issue by stuartlangridge** [robint99/mate-dock-applet#54]
If you click the Mutiny Launcher icon for the foreground application, that application gets minimised. Unity doesn't do this, and so it's very confusing when you're not used to it. (In Unity, if you click the Launcher icon for the foreground app and it has multiple windows, you get a window spread; if you click the Launcher icon for the foreground app and it has one window only, the click doesn't do anything.) I can see that this might be a useful feature to some, but I'd really like to be able to turn it off.

**Comment by robint99** [comment]
Implementing this shouldn't be a problem. I'll add a configuration option giving the choice of click action - minimise/restore windows or display a window spread :)

**Comment by robint99** [comment]
I've implemented this in the latest version of the applet (V0.75). Clicking an app's dock icon now works as follows:

- If the app isn't running, it gets started
- If the app only has one window open, the window is made active
- If the app has more than one window open, a list of the windows id displayed so that one can be selected

I've removed the old minimize/restore action because I think this works much better, so thanks for the suggestion :)
