### ISSUE TITLE
Invisible applet

### ISSUE THREAD

**Issue by VentGrey** [robint99/mate-dock-applet#83]
Im using debian testing and i make sure i was using the dependencies named here, however everytime i click the add button the dock never gets added, is the dock broken in Debian?

**Comment by robint99** [comment]
As far as I know the dock should work just fine in Debian testing. One thing to note though is If you're compiling from source then you'll need to add the --with-gtk3 switch when you run ./configure.  

If that doesn't help, open up a terminal and run 
`python3 /usr/lib/mate-applets/mate-dock-applet/dock_applet.py`
and let me know if what, if any, error messages you get.

Cheers

**Comment by Pival81** [comment]
I am also experiencing this with the latest mate release, 1.18

**Comment by ilgarmehmetali** [comment]
Experiencing this with arch linux, running it from terminal doesnt print anything.

**Comment by robint99** [comment]
The applet works on both Arch and on Mate 1.18, so I think the problem may be that you some dock applet processes already running from previous attempts to add it to the panel. These need to be killed :

`ps aux | grep dock_applet.py`

e.g.

![screenshot at 2017-03-22 09-08-21](https://cloud.githubusercontent.com/assets/10033637/24190016/2396fede-0edf-11e7-9cd3-9f0a67c7a273.png)

You should get a dialog box informing you that the applet has crashed, and you need to select the 'Delete' option. If you don't get the dialog, the applet process may not have been killed so try using `kill -9` or `kill -15` instead.

Once you've got rid of the old processes, you can then run 'python3 /usr/lib/mate-applets/mate-dock-applet/dock_applet.py' again and adding a dock to the panel should actually produce some output.

Hope this helps...

**Comment by Isakku** [comment]
I think I happen to know what's going on here. I just tried to install v0.77 in another machine and had the same problem: the applet didn't show up. So, instead of downloading the source code and compiling I tried using the  webupd8 repository and I found out that I was still missing dependencies. So, that means  in fact the list at the readme.md should be updated. 
These are the packages that were installed in my system after all:

gir1.2-wnck-1.0
libpcrecpp0
libpcre3-dev
zlib1g-dev
libglib2.0-dev
python3-cairo-dev
gir1.2-keybinder-0.0
python-wnck
python3-decorator
python3-numpy
python3-scipy
I suppose none of them belongs to another app. I had to check for the latest installed packages list to see what was missing.

**Comment by robint99** [comment]
Thanks for the info. I presume you're using Linux Mint, so I've compiled the applet from source in a newly installed Linux Mint virtual machine.  I only had to install libglib2.0 (which also pulled in libpcre-3-dev, libprcre-32.3, libprecpp-v5, and zlib1g-dev) and gir1.2-keybinder-0.0. Everything worked after that. The other packages you listed were either dependencies of older versions of the applet (python3-numpy, python3-scipy) that are no longer needed, packages the applet doesn't need and has never needed (python-wnck, python3-decorator), or were already installed (gir1.2-wnck-1.0).

To avoid confusion in the future, I'll change the readme.md to explicitly list the package names for dependencies on Mint/Ubuntu. This should also help users of other distros find the packages in their own distributions. I'll also add the keybinder dependency which I forgot to with the last update...

Thanks again.
