### ISSUE TITLE
Super_L keybinding are being swallowed

### ISSUE THREAD

**Issue by flexiondotorg** [robint99/mate-dock-applet#91]
The key bindings to launch applications via `Super_L+1`, `Super_L+2` are being swallowed when other applications have `Super_L` bindings, such a [Brisk Menu](https://github.com/solus-project/brisk-menu).

This issue has been discussed a length for various implementation here - https://github.com/solus-project/brisk-menu/issues/55

I've like to kindly ask @vkareh is he can work his magic in `mate-dock-applet` as well please?

**Comment by vkareh** [comment]
@flexiondotorg - of course! I've always had something bound to `Super_L`, so I didn't even know that the Dock applet allowed `Super+1`, `Super+2`, etc. It'd be my pleasure to work on this!

**Comment by flexiondotorg** [comment]
@vkareh `Super+1` etc landed in 0.78 which is available in Ubuntu MATE 17.10 daily or you can build from source.

**Comment by vkareh** [comment]
@flexiondotorg - yeah, I built from source and I can definitely see the issue on my side. I'm trying out different techniques, but I think they all revolve around the same concept: the keybinder library is looking at global events, but the applet itself is constraining which windows to get event reports from.

Research continues :)

**Comment by robint99** [comment]
I've been busy over the past few days so apologies for not joining this
discussion more promptly.

Now that I've had a chance to look at solus-project/brisk-menu#55
<https://github.com/solus-project/brisk-menu/issues/55> my understanding is
that the applet needs to propagate X keyboard events to other windows. I
don't believe the Keybinder library allows this sort of thing.

Therefore, maybe the best way forward would to be take the code from some
other project that does the same sort of thing (the Brisk menu perhaps...)
and convert it to Python? I've never done any X event coding before but in
the absence of any other volunteers would be happy to start  😉

How does this sound?

**Comment by vkareh** [comment]
@robint99 - you just brought up an interesting point: propagating events. I was thinking more along the lines of accepting events propagated from other windows. I'll play a bit and see where it leads.

The problem with taking an existing solution is that, at least for my current approach, the python-xlib library seems to require the shapes extension to call the correct Xlib function, whereas in straight Xlib (in C) the functionality is available for any window.

[mate-menu](https://bitbucket.org/ubuntu-mate/mate-menu) does some of this in python already, but to be honest I haven't tested whether it receives event reports from other windows (I have a strong feeling it doesn't)

Back to your point, Keybinder does not do this, but I'm not ready yet to drop it in favor of plain Xlib if the issue is not there.

**Comment by vkareh** [comment]
@robint99 I just confirmed the mate-menu has the same issue: if its shortcut is set to `<Super>somethingelse`, it gets swallowed when, say, brisk-menu is set to `<Super>`. So whatever we manage to fix in one, we should apply in the other.

I've started rewriting the keybinding logic in mate-dock-applet, but I'm wondering if we should not fix the python Keybinder library instead?

**Comment by vkareh** [comment]
going crazy here with python-xlib, then realized the python-xlib version in the ubuntu repos is about 8 years old!! I'm going the gdk route instead for the time being... :roll_eyes: 

If all else fails, we can write our own python binding for that single xlib function we need...

**Comment by vkareh** [comment]
Okay, I managed to sort-of "fix" it for mate-menu by using [XChangeWindowAttributes](https://tronche.com/gui/x/xlib/window/XChangeWindowAttributes.html) directly (essentially emulating what [XSelectInput](https://cgit.freedesktop.org/xorg/lib/libX11/tree/src/SelInput.c) does), but there seems to be a weird issue whenever the keyboard event is reported: CPU goes way up! I think mate-settings-daemon and mate-menu end up sending the same event back and forth to each other or something like that...

So I tried, unsuccessfully, to fix it on mate-dock-applet without changing anything else in the code. Either the Keybinder library has issues with it, or the fact that it uses wnck makes it behave differently with regards to reported events.

Next thing I'll try: get the applet window XID from wnck, and using that to get a reference to that same window from XLib, then do the `XChangeWindowAttributes` to it, rather than the root window.

**Comment by vkareh** [comment]
@flexiondotorg, @robint99 - I've submitted a pull request for this. I copied and adapted the code from mate-menu for this, and to be entirely honest, it feels a bit hacky. It works, though. Please test and let me know if changes are needed.

**Comment by flexiondotorg** [comment]
@vkareh Nice! I've tested the patch, works perfectly. In fact, I've patched the `mate-dock-applet` packaging for Debian and Ubuntu and uploaded the patched version to the Ubuntu archive.
