### ISSUE TITLE
v0.78 runs, v.0.79 doesn't, new deps ?

### ISSUE THREAD

**Issue by kajzersoze** [robint99/mate-dock-applet#99]
I was able to run all versions prior to 0.79 but this one just doesn't work, dock doesn't appear.
If I'm understanding what's going on correctly, keybinder dependency is no longer needed starting from 0.79 and instead there's python-xlib, however with that lib installed it still doesn't show, anything else I'm missing ?

**Comment by Isakku** [comment]
Uhm, perhaps you could add more details such as what mate version you are using to your report?
I don't have the problems you have, at least not exactly. I had recently installed linux mint mate 18.2 and the webupdate version didn't work at all. I had to download the source code and compile it using gtk3 option (because the new version of mate has become gtk3) and only then it began to work.

**Comment by kajzersoze** [comment]
Mate version is 1.18

btw I had the same problem when I was switching to 0.77, but there was a notice about a new dependency :

> New Dependency
> 
> Finally, package maintainers need to note a new dependency of the applet - Keybinder. For example, on Arch Linux this is the libkeybinder-3.0 package, on Ubuntu 16.04 it is gir1.2-keybinder-0.0 and on Ubtuntu 16.10, gir1.2-keybinder-3.0
> 

There is nothing like that for 0.79
I'm on Gentoo and I compile every version, but compiling v0.79 and the git master doesn't work, I mean compiling works but dock isn't starting.

**Comment by kajzersoze** [comment]
Solved it, I've installed stable version of python-xlib which is old and that's why it wasn't working, when I installed latest version of it all was good.
